# Generated by Django 3.2.4 on 2021-06-14 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='APPLICATION_STATUS',
            new_name='application_status',
        ),
        migrations.AddField(
            model_name='profile',
            name='region_of_residence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region'),
        ),
    ]
