# Generated by Django 3.2.4 on 2021-09-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='attached_region',
        ),
    ]
