# Generated by Django 3.2.4 on 2021-09-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profiledeployment_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='type',
            field=models.CharField(choices=[('language', 'LANGUAGE'), ('work', 'WORK')], default='work', max_length=100),
        ),
    ]
