# Generated by Django 3.2.4 on 2021-09-22 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_attached_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attached_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
