# Generated by Django 3.2.4 on 2021-11-14 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211111_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attached_region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
            preserve_default=False,
        ),
    ]
