# Generated by Django 3.2.4 on 2021-06-17 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='application_status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='competencies',
            field=models.ManyToManyField(null=True, to='core.Competence'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?[0-9- ]{8,15}$', 'Enter a valid phone number.')]),
        ),
    ]
