# Generated by Django 3.2.4 on 2022-03-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profileacademicqualification_field_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileacademicqualification',
            name='qualification_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicqualificationtype'),
        ),
    ]
