# Generated by Django 3.2.4 on 2021-07-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbreak',
            name='competencies',
            field=models.ManyToManyField(blank=True, null=True, related_name='outbreaks', to='core.Competence'),
        ),
        migrations.AlterField(
            model_name='outbreak',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profiledeployment',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
