# Generated by Django 3.2.4 on 2022-03-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profileacademicqualification_qualification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='next_of_kin_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='next_of_kin_phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='next_of_kin',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='professional_experience',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
