# Generated by Django 3.2.4 on 2022-03-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220307_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='application_status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approval_complete', 'Approval Complete'), ('rejected', 'Rejected')], default='pending_approval', max_length=255),
        ),
    ]
