# Generated by Django 3.2.4 on 2021-09-19 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210919_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attached_region',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
            preserve_default=False,
        ),
    ]
