# Generated by Django 3.2.4 on 2022-03-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_type_outbreak_outbreak_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledeployment',
            name='accepted_by_user',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
