# Generated by Django 3.2.4 on 2022-03-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profiledeployment_deployment_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledeployment',
            name='rejected_by_user',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
