# Generated by Django 3.2.4 on 2022-04-15 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0016_profiledeployment_rejected_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='outbreak',
            name='eligibility_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profileacademicqualification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='profile_academic_qualifications', to='core.profile'),
        ),
    ]
