# Generated by Django 3.2.4 on 2022-04-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0017_auto_20220415_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='previous_deployments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
