# Generated by Django 3.2.4 on 2022-04-17 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0018_profile_previous_deployments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='previous_deployments',
            new_name='previous_deployment_experience',
        ),
    ]
