# Generated by Django 3.2.4 on 2022-04-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0019_rename_previous_deployments_profile_previous_deployment_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbreak',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
