# Generated by Django 3.2.4 on 2022-04-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0020_outbreak_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='other_region',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
