# Generated by Django 3.2.4 on 2022-04-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0021_user_other_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
