# Generated by Django 3.2.4 on 2022-05-03 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0023_abstractdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_photo',
            field=models.FileField(blank=True, null=True, upload_to='passport/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='abstractdocument',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='abstract_reports/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='outbreak',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='outbreak_reports/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='application_status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('rejected', 'Rejected'),
                                            ('approval_complete', 'Approval Complete')], default='pending_approval',
                                   max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profiledeployment',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.AlterField(
            model_name='profiledeployment',
            name='status',
            field=models.CharField(
                choices=[('initiated', 'Initiated'), ('pre_deployment', 'Pre Deployment'), ('deployed', 'Deployed'),
                         ('ended', 'Ended')], default='initiated', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
