# Generated by Django 3.2.4 on 2022-05-03 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0024_auto_20220503_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_confirmed',
        ),
    ]
