# Generated by Django 3.2.4 on 2022-05-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0025_remove_user_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
