# Generated by Django 3.2.4 on 2022-05-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0026_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
