# Generated by Django 3.2.4 on 2022-06-23 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0029_alter_region_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='competencies',
            field=models.ManyToManyField(blank=True, null=True, to='core.Competence'),
        ),
        migrations.CreateModel(
            name='DetailedExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience_type', models.CharField(choices=[('managerial_experience', 'Managerial Experience'),
                                                              ('professional_experience', 'Professional Experience')],
                                                     max_length=255)),
                ('years_of_experience', models.CharField(
                    choices=[('1-4', '1 To 4 Years'), ('5-10', '5 To 10 Years'), ('over-10', 'Over 10 Years')],
                    max_length=255)),
                ('no_of_people_managed', models.CharField(
                    choices=[('1-4', '1 To 4 People'), ('5-10', '5 To 10 People'), ('10-20', '10 To 20 Years'),
                             ('over-20', 'Over 20 Years')], max_length=255)),
                ('profile',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
