# Generated by Django 3.2.4 on 2022-06-23 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0030_auto_20220623_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedexperience',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.occupation'),
        ),
    ]
