# Generated by Django 3.2.4 on 2022-06-23 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0032_auto_20220623_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelanguage',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
        migrations.AlterField(
            model_name='profilelanguage',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
            preserve_default=False,
        ),
    ]
