# Generated by Django 3.2.4 on 2022-06-24 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0033_auto_20220624_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='occupation_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='core.occupationcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialization',
            name='occupation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.occupation'),
            preserve_default=False,
        ),
    ]
